# Generated by Django 4.2 on 2023-07-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_menu_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
